package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/chenhg5/cc-connect/daemon"
)

func runSetup(args []string) {
	fs := flag.NewFlagSet("setup", flag.ExitOnError)
	token := fs.String("token", "", "WeChat iLink Bot token")
	allowFrom := fs.String("allow-from", "", "allowed WeChat user IDs (comma-separated, * for all)")
	accountID := fs.String("account-id", "default", "account label for multi-account isolation")
	claudePath := fs.String("claude-path", "", "path to claude binary")
	noDaemon := fs.Bool("no-daemon", false, "skip daemon installation")
	configPath := fs.String("config-path", "", "custom config file path")
	force := fs.Bool("force", false, "overwrite existing config without prompting")
	_ = fs.Parse(args)

	interactive := *token == ""

	fmt.Println(strings.Repeat("=", 52))
	fmt.Println("  cc-connect setup — Claude Code + WeChat")
	fmt.Println(strings.Repeat("=", 52))
	fmt.Println()

	// Step 1: Detect Claude Code
	fmt.Println("[1/4] Detecting Claude Code...")
	claudeBin := *claudePath
	if claudeBin == "" {
		claudeBin = detectClaudeCode()
	}
	if claudeBin == "" {
		if interactive {
			fmt.Print("Claude Code not found in PATH. Enter path to claude binary (or press Enter to skip): ")
			scanner := bufio.NewScanner(os.Stdin)
			if scanner.Scan() {
				claudeBin = strings.TrimSpace(scanner.Text())
			}
		}
	}
	if claudeBin != "" {
		ver := getClaudeVersion(claudeBin)
		fmt.Printf("  Found: %s (%s)\n", claudeBin, ver)
	} else {
		fmt.Println("  Skipped. Claude Code must be installed separately.")
	}
	fmt.Println()

	// Step 2: WeChat token
	fmt.Println("[2/4] Configuring WeChat connection...")
	botToken := *token
	if botToken == "" && interactive {
		fmt.Print("Enter WeChat iLink Bot token: ")
		scanner := bufio.NewScanner(os.Stdin)
		if scanner.Scan() {
			botToken = strings.TrimSpace(scanner.Text())
		}
	}
	if botToken == "" {
		fmt.Fprintln(os.Stderr, "Error: WeChat bot token is required. Use --token flag or enter interactively.")
		os.Exit(1)
	}
	fmt.Println("  Token configured.")
	fmt.Println()

	// Step 3: Generate config
	fmt.Println("[3/4] Generating configuration...")
	cfgDir := configDir()
	cfgFile := *configPath
	if cfgFile == "" {
		cfgFile = filepath.Join(cfgDir, "config.toml")
	}

	if _, err := os.Stat(cfgFile); err == nil && !*force {
		if interactive {
			fmt.Printf("Config file already exists at %s\n", cfgFile)
			fmt.Print("Overwrite? [y/N]: ")
			scanner := bufio.NewScanner(os.Stdin)
			if !scanner.Scan() || strings.ToLower(strings.TrimSpace(scanner.Text())) != "y" {
				fmt.Println("  Skipped config generation.")
				fmt.Println()
				return
			}
		}
	}

	if err := os.MkdirAll(cfgDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating config directory: %v\n", err)
		os.Exit(1)
	}

	allowFromLine := ""
	if *allowFrom != "" {
		allowFromLine = fmt.Sprintf("\nallow_from = \"%s\"", *allowFrom)
	}

	claudeOpts := ""
	if claudeBin != "" {
		claudeOpts = fmt.Sprintf("\n[projects.agent.options]\nbinary_path = \"%s\"", claudeBin)
	}

	cfg := fmt.Sprintf(`# cc-connect — Claude Code + WeChat
# Generated by cc-connect setup

language = "zh-CN"
data_dir = "%s"

[[projects]]
name = "default"

[projects.agent]
type = "claudecode"%s

[[projects.platforms]]
type = "weixin"
[projects.platforms.options]
token = "%s"
account_id = "%s"%s

[log]
level = "info"
`, filepath.ToSlash(filepath.Join(cfgDir, "data")), claudeOpts, botToken, *accountID, allowFromLine)

	if err := os.WriteFile(cfgFile, []byte(cfg), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing config: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("  Config written to %s\n", cfgFile)
	fmt.Println()

	// Step 4: Daemon installation
	fmt.Println("[4/4] System service...")
	if *noDaemon {
		fmt.Println("  Skipped (--no-daemon).")
		fmt.Println()
		printFinish(cfgFile)
		return
	}

	if interactive {
		fmt.Print("Install as system service (auto-start on login)? [Y/n]: ")
		scanner := bufio.NewScanner(os.Stdin)
		if scanner.Scan() {
			answer := strings.ToLower(strings.TrimSpace(scanner.Text()))
			if answer == "n" || answer == "no" {
				fmt.Println("  Skipped.")
				fmt.Println()
				printFinish(cfgFile)
				return
			}
		}
	}

	mgr, err := daemon.NewManager()
	if err != nil {
		fmt.Println("  Service management not supported on this platform.")
		fmt.Println()
		printFinish(cfgFile)
		return
	}

	dcfg := daemon.Config{
		WorkDir: cfgDir,
	}
	if err := daemon.Resolve(&dcfg); err != nil {
		fmt.Fprintf(os.Stderr, "  Error resolving daemon config: %v\n", err)
		os.Exit(1)
	}

	if err := mgr.Install(dcfg); err != nil {
		fmt.Fprintf(os.Stderr, "  Error installing service: %v\n", err)
	} else {
		if err := daemon.SaveMeta(&daemon.Meta{
			LogFile:     dcfg.LogFile,
			LogMaxSize:  dcfg.LogMaxSize,
			WorkDir:     dcfg.WorkDir,
			BinaryPath:  dcfg.BinaryPath,
			InstalledAt: daemon.NowISO(),
		}); err != nil {
			fmt.Fprintf(os.Stderr, "  Warning: failed to save metadata: %v\n", err)
		}
		fmt.Printf("  Service installed (%s).\n", mgr.Platform())
	}

	fmt.Println()
	printFinish(cfgFile)
}

func detectClaudeCode() string {
	if p, err := exec.LookPath("claude"); err == nil {
		return p
	}
	home, _ := os.UserHomeDir()
	candidates := []string{}
	if runtime.GOOS == "windows" {
		candidates = []string{
			filepath.Join(home, "AppData", "Roaming", "npm", "claude.cmd"),
			filepath.Join(home, "AppData", "Local", "claude", "claude.exe"),
		}
	} else {
		candidates = []string{
			"/usr/local/bin/claude",
			filepath.Join(home, ".local", "bin", "claude"),
			filepath.Join(home, "bin", "claude"),
		}
	}
	for _, p := range candidates {
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	return ""
}

func getClaudeVersion(path string) string {
	cmd := exec.Command(path, "--version")
	out, err := cmd.Output()
	if err != nil {
		return "unknown"
	}
	return strings.TrimSpace(string(out))
}

func configDir() string {
	if runtime.GOOS == "windows" {
		appData := os.Getenv("APPDATA")
		if appData == "" {
			home, _ := os.UserHomeDir()
			appData = filepath.Join(home, "AppData", "Roaming")
		}
		return filepath.Join(appData, ".cc-connect")
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".cc-connect")
}

func printFinish(cfgFile string) {
	fmt.Println(strings.Repeat("=", 52))
	fmt.Println("  Setup complete!")
	fmt.Println()
	fmt.Printf("  Config: %s\n", cfgFile)
	fmt.Printf("  Start:  cc-connect --config %s\n", cfgFile)
	fmt.Println()
	fmt.Println("  Useful commands:")
	fmt.Println("    cc-connect daemon start        Start the service")
	fmt.Println("    cc-connect daemon stop         Stop the service")
	fmt.Println("    cc-connect daemon status       Check service status")
	fmt.Println("    cc-connect daemon logs         View logs")
	fmt.Println(strings.Repeat("=", 52))
}
