package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"
)

func runSetup(args []string) {
	fs := flag.NewFlagSet("setup", flag.ExitOnError)
	token := fs.String("token", "", "existing WeChat iLink Bot token (skip QR scan)")
	allowFrom := fs.String("allow-from", "", "allowed WeChat user IDs (comma-separated, * for all)")
	claudePath := fs.String("claude-path", "", "path to claude binary")
	configPath := fs.String("config-path", "", "custom config file path")
	force := fs.Bool("force", false, "overwrite existing config without prompting")
	_ = fs.Parse(args)

	interactive := *token == ""

	fmt.Println(strings.Repeat("=", 52))
	fmt.Println("  cc-connect setup — Claude Code + WeChat")
	fmt.Println(strings.Repeat("=", 52))
	fmt.Println()

	// Step 1: Detect Claude Code
	fmt.Println("[1/3] Detecting Claude Code...")
	claudeBin := *claudePath
	if claudeBin == "" {
		claudeBin = detectClaudeCode()
	}
	if claudeBin == "" {
		if interactive {
			fmt.Print("Claude Code not found in PATH. Enter path to claude binary (or press Enter to skip): ")
			scanner := bufio.NewScanner(os.Stdin)
			if scanner.Scan() {
				claudeBin = strings.TrimSpace(scanner.Text())
			}
		}
	}
	if claudeBin != "" {
		ver := getClaudeVersion(claudeBin)
		fmt.Printf("  Found: %s (%s)\n", claudeBin, ver)
	} else {
		fmt.Println("  Skipped. Claude Code must be installed separately.")
	}
	fmt.Println()

	// Step 2: WeChat connection via QR scan
	fmt.Println("[2/3] Configuring WeChat connection...")
	var (
		botToken  string
		accountID string
		baseURL   string
	)

	if *token != "" {
		botToken = *token
		accountID = "default"
		baseURL = ""
		fmt.Println("  Using provided token.")
	} else if interactive {
		fmt.Println("  How would you like to connect?")
		fmt.Println("    [1] Scan QR code with WeChat (recommended)")
		fmt.Println("    [2] Paste an existing iLink Bot token")
		fmt.Println("    [3] Enter a token")
		fmt.Print("  Choice [1]: ")
		scanner := bufio.NewScanner(os.Stdin)
		choice := "1"
		if scanner.Scan() {
			choice = strings.TrimSpace(scanner.Text())
			if choice == "" {
				choice = "1"
			}
		}

		switch choice {
		case "2", "3":
			fmt.Print("  Enter WeChat iLink Bot token: ")
			if scanner.Scan() {
				botToken = strings.TrimSpace(scanner.Text())
			}
			accountID = "default"
		default:
			fmt.Println()
			fmt.Println("  A QR code will appear below. Scan it with your WeChat app.")
			fmt.Println("  Waiting for scan (timeout: 8 minutes)...")
			fmt.Println()

			res, err := runWeixinQRLoginFlow(weixinQRLoginOptions{
				APIBaseURL: defaultWeixinAPIURL,
				BotType:    defaultWeixinBotType,
				Timeout:    480 * time.Second,
			})
			if err != nil {
				fmt.Fprintf(os.Stderr, "\nError: QR login failed: %v\n", err)
				fmt.Fprintln(os.Stderr, "Tip: you can retry with: cc-connect setup")
				fmt.Fprintln(os.Stderr, "     or use an existing token: cc-connect setup --token <token>")
				os.Exit(1)
			}
			botToken = res.BotToken
			accountID = res.IlinkBotID
			if res.BaseURL != "" {
				baseURL = res.BaseURL
			}
		}
	}

	if botToken == "" {
		fmt.Fprintln(os.Stderr, "Error: WeChat bot token is required.")
		os.Exit(1)
	}
	fmt.Println()
	fmt.Println("  WeChat connection configured.")
	fmt.Println()

	// Step 3: Generate config
	fmt.Println("[3/3] Generating configuration...")
	cfgDir := configDir()
	cfgFile := *configPath
	if cfgFile == "" {
		cfgFile = filepath.Join(cfgDir, "config.toml")
	}

	if _, err := os.Stat(cfgFile); err == nil && !*force {
		if interactive {
			fmt.Printf("Config file already exists at %s\n", cfgFile)
			fmt.Print("Overwrite? [y/N]: ")
			scanner := bufio.NewScanner(os.Stdin)
			if !scanner.Scan() || strings.ToLower(strings.TrimSpace(scanner.Text())) != "y" {
				fmt.Println("  Skipped config generation.")
				fmt.Println()
				return
			}
		}
	}

	if err := os.MkdirAll(cfgDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating config directory: %v\n", err)
		os.Exit(1)
	}

	if accountID == "" {
		accountID = "default"
	}

	allowFromLine := ""
	if *allowFrom != "" {
		allowFromLine = fmt.Sprintf("\nallow_from = \"%s\"", *allowFrom)
	}

	baseURLLine := ""
	if baseURL != "" && baseURL != defaultWeixinAPIURL {
		baseURLLine = fmt.Sprintf("\nbase_url = \"%s\"", baseURL)
	}

	claudeOpts := ""
	if claudeBin != "" {
		claudeOpts = fmt.Sprintf("\n[projects.agent.options]\nbinary_path = \"%s\"", claudeBin)
	}

	cfg := fmt.Sprintf(`# CC2Wechat — Claude Code + WeChat
# Generated by cc-connect setup

language = "zh-CN"
data_dir = "%s"

[[projects]]
name = "default"

[projects.agent]
type = "claudecode"%s

[[projects.platforms]]
type = "weixin"
[projects.platforms.options]
token = "%s"
account_id = "%s"%s%s

[log]
level = "info"
`, filepath.ToSlash(filepath.Join(cfgDir, "data")), claudeOpts, botToken, accountID, baseURLLine, allowFromLine)

	if err := os.WriteFile(cfgFile, []byte(cfg), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing config: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("  Config written to %s\n", cfgFile)
	fmt.Println()

	fmt.Println(strings.Repeat("=", 52))
	fmt.Println("  Setup complete! Starting cc-connect...")
	fmt.Println(strings.Repeat("=", 52))
	fmt.Println()
}

func detectClaudeCode() string {
	if p, err := exec.LookPath("claude"); err == nil {
		return p
	}
	home, _ := os.UserHomeDir()
	candidates := []string{}
	if runtime.GOOS == "windows" {
		candidates = []string{
			filepath.Join(home, "AppData", "Roaming", "npm", "claude.cmd"),
			filepath.Join(home, "AppData", "Local", "claude", "claude.exe"),
		}
	} else {
		candidates = []string{
			"/usr/local/bin/claude",
			filepath.Join(home, ".local", "bin", "claude"),
			filepath.Join(home, "bin", "claude"),
		}
	}
	for _, p := range candidates {
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	return ""
}

func getClaudeVersion(path string) string {
	cmd := exec.Command(path, "--version")
	out, err := cmd.Output()
	if err != nil {
		return "unknown"
	}
	return strings.TrimSpace(string(out))
}

func configDir() string {
	if runtime.GOOS == "windows" {
		appData := os.Getenv("APPDATA")
		if appData == "" {
			home, _ := os.UserHomeDir()
			appData = filepath.Join(home, "AppData", "Roaming")
		}
		return filepath.Join(appData, ".cc-connect")
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".cc-connect")
}

